// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjyqqkcompuvtnakwexh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqeXFxa2NvbXB1dnRuYWt3ZXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mzk2OTIsImV4cCI6MjA2MjAxNTY5Mn0.gDopEEXfu-T9OjYTvVlwBMhM_cDq6cmcfZZ5eHZt2RE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);